[package]
org = "poorna"
name = "mod_conf"
version = "0.1.0"
distribution = "2201.10.0"

org = "nuvin"
name = "mod_conf_2"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true
